version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Listener interno Docker
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Listener que los clientes externos usarán (ngrok)
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://6.tcp.eu.ngrok.io:19302
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"   # expone el puerto interno al host para que ngrok lo tome
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:
    driver: local
